name: production_deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: SSH in production server
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd /var/www/html/proscholy-web && make production-deploy --silent
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
