name: production_deploy
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_COLOR: '#3961ad'
          SLACK_WEBHOOK: ${{ secrets.SLACK_DEPLOYS_WEBHOOK_URL }}
          SLACK_FOOTER: ''
          MSG_MINIMAL: true
          SLACK_TITLE: '${{ env.GITHUB_WORKFLOW }} – ${{ github.event.repository.name }}'
          SLACK_MESSAGE: 'Proběhl testovací deploy na zpevnik.proscholy.cz! :tada:'
